language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - png-editor/scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

branches:
    except:
        - gh-pages

script:
  - karma start png-editor/config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start png-editor/config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
