language: node_js
node_js:
  - "0.10"

env:
  global:
    # See http://about.travis-ci.org/docs/user/encryption-keys/
    secure: |-
      bcpk162HGtlg4JY43YpoTDPGWfoTMAPnozjw08TSUkFpO8mG+kEb92GUqYFp
      yb7Tlfz3Jk/yE+NPbMfcxjOHy6ncO9xjcs7OYZAO2RgdaatHFIibKoMBhuPz
      1OfVVd1Rw1/KNuOOFt/65VdNsLGecYwA7/SVuQ5EIavY29rmISM=

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - bash -c "cd png-editor && scripts/web-server.js > /dev/null" &
  - sleep 1 # give server time to start

branches:
    except:
        - gh-pages

script:
  - karma start png-editor/config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - karma start png-editor/config/karma-e2e.conf.js --reporters=dots --browsers=Firefox

after_success:
  - png-editor/scripts/post_build.sh